"use client";
import Link from "next/link";
import { useState } from "react";
import { errorRecovery } from "@studify/study-core/recovery";
import { AppShell } from "@/components/app-shell";
import { useStudyData } from "@/lib/study-store";
import { localDate } from "@/lib/study-data";
import { useQuestionCollections } from "@/lib/question-collections";
import { secondaryButtonClass } from "@/components/study-ui";
export default function ReviewsPage() {
  const { data } = useStudyData();
  const [tab, setTab] = useState("pending");
  const recovery = errorRecovery(data.attempts);
  const collections = useQuestionCollections();
  const today = localDate(new Date());
  const tasks = data.tasks.filter(t => !t.completedAt && (tab !== "recall" || t.kind === "recall")).sort((a,b) => a.dueDate.localeCompare(b.dueDate));
  return <AppShell><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-semibold">Erros & Revisões</h1><p className="mt-3 text-muted">Transforme erros em próximos passos e teste o que consegue recuperar de memória.</p><dl className="mt-6 flex flex-wrap gap-6 border-y border-line py-5">{[["Erros registrados",recovery.registered],["Refazidos",recovery.retried],["Recuperados",recovery.recovered],["Recuperação",recovery.rate === null ? "Sem novas tentativas" : `${Math.round(recovery.rate * 100)}%`]].map(([label,value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>)}</dl><p className="mt-2 text-xs text-muted">Questões distintas: recuperadas quando a última tentativa após um erro está correta. Taxa = recuperadas ÷ refazidas.</p><nav aria-label="Revisões" className="my-5 flex flex-wrap gap-2">{[["pending","Revisões pendentes"],["recall","Recalls"],["wrong","Questões erradas"],["recovered","Erros recuperados"],["favorites","Favoritas"],["notes","Anotações"]].map(([id,label]) => <button key={id} aria-pressed={tab === id} onClick={() => setTab(id)} className={secondaryButtonClass}>{label}</button>)}</nav>
  {(tab === "pending" || tab === "recall") && <section>{tasks.length ? tasks.map(task => <article key={task.id} className="flex flex-wrap justify-between gap-3 border-b border-line py-4"><div><h2 className="font-medium">{data.subjects.find(s => s.id === task.subjectId)?.name} · {task.kind === "recall" ? "Recall" : "Revisão"}</h2><p className="mt-1 text-sm text-muted">{data.topics.find(t => t.id === task.topicId)?.title ?? "Conteúdo da sessão"} · {task.dueDate < today ? "Atrasada" : task.dueDate === today ? "Hoje" : task.dueDate.split("-").reverse().join("/")}</p></div><Link href={`/estudos?task=${task.id}`} className="text-accent">{task.kind === "recall" ? "Recuperar de memória" : "Revisar agora"} →</Link></article>) : <p className="py-5 text-muted">Nenhuma tarefa pendente. Finalize uma sessão para programar revisões e recalls.</p>}</section>}
  {(tab === "wrong" || tab === "recovered") && <section>{recovery.questions.filter(q => tab === "recovered" ? q.recovered : !q.recovered).map(q => { const attempt = data.attempts.find(a => a.id === q.latestAttempt.id); return <article key={q.questionId} className="border-b border-line py-4"><h2>{data.subjects.find(s => s.id === attempt?.subjectId)?.name ?? "Questão"} · {data.topics.find(t => t.id === attempt?.topicId)?.title ?? "Sem tópico"}</h2><p className="text-sm text-muted">{q.attemptsAfterError} novas tentativas · {q.recovered ? "Recuperado" : "Revisar"}</p><Link href={`/questoes?subject=${attempt?.subjectId ?? ""}&status=${q.recovered ? "correct" : "wrong"}`} className="mt-2 inline-block text-sm text-accent">Refazer questões deste assunto →</Link></article>; })}{!recovery.questions.some(q => tab === "recovered" ? q.recovered : !q.recovered) && <p className="py-5 text-muted">Ainda não há {tab === "recovered" ? "erros recuperados" : "erros pendentes"} no histórico de questões.</p>}</section>}
  {tab === "notes" && <section>{data.sessions.filter(s => s.notes.trim()).map(s => <article key={s.id} className="border-b border-line py-4"><h2>{data.subjects.find(subject => subject.id === s.subjectId)?.name} · {new Date(s.endedAt).toLocaleDateString("pt-BR")}</h2><p className="mt-2 whitespace-pre-wrap break-words text-sm text-secondary">{s.notes}</p><Link href={`/estudos?subject=${s.subjectId}${s.topicId ? `&topic=${s.topicId}` : ""}`} className="mt-2 inline-block text-sm text-accent">Refazer assunto</Link></article>)}{!data.sessions.some(s => s.notes.trim()) && <p className="py-5 text-muted">Anote aprendizados ao finalizar uma sessão para encontrá-los aqui.</p>}</section>}
  {tab === "favorites" && <section><p className="py-4 text-muted">{collections.error || `${collections.favorites.length} favoritas salvas na sua conta.`}</p><Link href="/questoes?status=favorite" className="text-accent">Resolver favoritas →</Link></section>}
  </div></AppShell>;
}
