"use client";

import { AppShell } from "@/components/app-shell";
import { EmptyState, timeLabel } from "@/components/study-ui";
import { calculateMetrics, calculateTopicMetrics } from "@/lib/priority-engine";
import { useStudyData } from "@/lib/study-store";

export default function AnalisesPage() {
  const { data } = useStudyData();
  const metrics = calculateMetrics(data);
  const topics = calculateTopicMetrics(data);
  const weak = topics.filter((topic) => topic.questions >= 5 && topic.accuracy !== null && topic.accuracy < 0.7).sort((a, b) => a.accuracy! - b.accuracy!);
  return <AppShell><div className="mx-auto max-w-5xl"><header className="border-b border-line pb-5"><p className="text-sm text-muted">Semana atual</p><h1 className="mt-1 text-3xl font-semibold">O que seu estudo mostra</h1><p className="mt-3 text-sm text-muted">Planejado e executado, com base nas sessões e nas respostas registradas.</p></header>{!data.subjects.length ? <div className="py-8"><EmptyState title="Os dados começam na primeira sessão" description="Adicione uma matéria e registre seus estudos. Nenhuma métrica será preenchida com dados fictícios." href="/materias" action="Adicionar matérias" /></div> : <>
    <dl className="flex flex-wrap gap-x-10 gap-y-4 border-b border-line py-6">{[["Tempo líquido",timeLabel(metrics.executedSeconds)],["Planejado",timeLabel(metrics.plannedSeconds)],["Execução",metrics.executionRate === null ? "Sem plano" : `${Math.round(metrics.executionRate * 100)}%`],["Questões",String(metrics.questions)],["Acertos",metrics.accuracy === null ? "Sem respostas" : `${Math.round(metrics.accuracy * 100)}%`]].map(([label,value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="mt-2 text-xl font-semibold">{value}</dd></div>)}</dl>
    <section className="border-b border-line py-6"><h2 className="text-xl font-semibold">Planejado × executado por matéria</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Tempo e acertos por matéria nesta semana</caption><thead className="border-b border-line text-xs text-muted"><tr>{["Matéria","Planejado","Executado","Questões","Acertos"].map((label) => <th key={label} scope="col" className="whitespace-nowrap px-2 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-line">{metrics.bySubject.map((subject) => <tr key={subject.subjectId}><th scope="row" className="px-2 py-4 font-medium">{subject.name}</th><td className="whitespace-nowrap px-2 text-muted">{timeLabel(subject.plannedSeconds)}</td><td className="whitespace-nowrap px-2 text-accent">{timeLabel(subject.executedSeconds)}</td><td className="px-2 text-secondary">{subject.questions}</td><td className="px-2 text-secondary">{subject.accuracy === null ? "—" : `${subject.correct}/${subject.questions} (${Math.round(subject.accuracy * 100)}%)`}</td></tr>)}</tbody></table></div></section>
    <section className="border-b border-line py-6"><h2 className="text-xl font-semibold">Ritmo da semana</h2><div className="mt-4 space-y-3">{metrics.daily.map((day) => { const max = Math.max(day.plannedSeconds, day.executedSeconds, 1); return <div key={day.date} className="grid grid-cols-[3rem_1fr] items-center gap-3"><span className="text-xs text-muted">{new Date(`${day.date}T12:00:00`).toLocaleDateString("pt-BR", { weekday: "short" })}</span><div><div className="mb-1 flex flex-wrap justify-between gap-2 text-xs"><span className="text-muted">Planejado {timeLabel(day.plannedSeconds)}</span><span className="text-accent">Executado {timeLabel(day.executedSeconds)}</span></div><div className="h-1 rounded-sm bg-raised"><div className="h-1 rounded-sm bg-line" style={{ width: `${day.plannedSeconds / max * 100}%` }} /></div><div className="mt-1 h-1 rounded-sm bg-raised"><div className="h-1 rounded-sm bg-primary" style={{ width: `${day.executedSeconds / max * 100}%` }} /></div></div></div>; })}</div></section>
    <section className="border-b border-line py-6"><h2 className="text-xl font-semibold">Tópicos que pedem atenção</h2><p className="mt-2 text-xs text-muted">Abaixo de 70% de acerto, com pelo menos 5 questões registradas. Amostras menores ainda não sustentam essa classificação.</p>{weak.length ? <ul className="mt-4 divide-y divide-line">{weak.map((topic) => <li key={topic.topicId} className="flex justify-between gap-3 py-3 text-sm"><span>{topic.topic}</span><span className="text-attention">{Math.round(topic.accuracy! * 100)}% · {topic.questions} questões</span></li>)}</ul> : <p className="mt-4 text-sm text-muted">Nenhum tópico classificado como fraco com a amostra atual.</p>}</section>
    <section className="py-6"><h2 className="text-xl font-semibold">Sessões recentes</h2>{data.sessions.length ? <ol className="mt-4 divide-y divide-line">{[...data.sessions].sort((a,b) => b.endedAt.localeCompare(a.endedAt)).slice(0,15).map((session) => <li key={session.id} className="py-3"><div className="flex flex-wrap justify-between gap-2 text-sm"><span className="font-medium">{data.subjects.find((subject) => subject.id === session.subjectId)?.name}</span><span className="text-muted">{new Date(session.endedAt).toLocaleDateString("pt-BR")} · {timeLabel(session.seconds)}</span></div>{session.notes && <p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-secondary">{session.notes}</p>}</li>)}</ol> : <p className="mt-4 text-sm text-muted">Ainda sem sessões registradas.</p>}</section>
  </>}</div></AppShell>;
}
